# Generated by Django 2.0.1 on 2018-10-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('taquiclave', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidopaterno', models.CharField(max_length=50)),
                ('apellidomaterno', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numinterior', models.BigIntegerField()),
                ('numexterior', models.BigIntegerField()),
                ('fechaprimervista', models.DateField()),
                ('numpuntos', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContenerDjango',
            fields=[
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('idcontener', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contener_django',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cpedocliente',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cpedocliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cpedosucursal',
            fields=[
                ('cp', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cpedosucursal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fechapedpromo',
            fields=[
                ('fechapedido', models.DateField(primary_key=True, serialize=False)),
                ('promocion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fechapedpromo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numpedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('metodopago', models.CharField(max_length=50)),
                ('preparado', models.BooleanField()),
                ('entregado', models.BooleanField()),
                ('fechapedido', models.ForeignKey(db_column='fechapedido', on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Fechapedpromo')),
            ],
            options={
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.BigIntegerField(primary_key=True, serialize=False)),
                ('horaapertura', models.DateTimeField()),
                ('horacierre', models.DateTimeField()),
                ('municipio', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numinterior', models.BigIntegerField()),
                ('numexterior', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('taquegoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productoleyenda',
            fields=[
                ('idproducto', models.ForeignKey(db_column='idproducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Producto')),
                ('leyenda', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productoleyenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursaltelefono',
            fields=[
                ('idsucursal', models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='inicio.Sucursal')),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursaltelefono',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cp',
            field=models.ForeignKey(db_column='cp', on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Cpedosucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idsucursal',
            field=models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Sucursal'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='taquiclave',
            field=models.ForeignKey(db_column='taquiclave', on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Cliente'),
        ),
        migrations.AddField(
            model_name='contenerdjango',
            name='idproducto',
            field=models.ForeignKey(blank=True, db_column='idproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Producto'),
        ),
        migrations.AddField(
            model_name='contenerdjango',
            name='numpedido',
            field=models.ForeignKey(blank=True, db_column='numpedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Pedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.ForeignKey(db_column='cp', on_delete=django.db.models.deletion.DO_NOTHING, to='inicio.Cpedocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productoleyenda',
            unique_together={('idproducto', 'leyenda')},
        ),
    ]
